### ISSUE TITLE
如何对需要跟踪的进行跟踪，不跟踪的只进行检测？

### ISSUE THREAD

**Issue by starsky68** [WuPedin/Multi-class_Yolov5_DeepSort_Pytorch#1]
@WuPedin 
作者你好，请问，如何对需要跟踪的进行跟踪，不跟踪的只进行检测？我看该项目似乎是对所有类进行跟踪的，我固定跟踪的类别，但是，会出现把不需要跟踪的类别进行跟踪。

**Comment by WuPedin** [comment]
Hi 
If you don't want to track some classes, you can modify codes in track.py in line 176. 
You can filter the detection results before deepsort.update().

For example:
`
classes2track = [0,2,4,6]

for *xyxy, conf, cls in det:
    if cls in classes2track:
        img_h, img_w, _ = im0.shape  # get image shape
        x_c, y_c, bbox_w, bbox_h = bbox_rel(img_w, img_h, *xyxy)
        obj = [x_c, y_c, bbox_w, bbox_h]
        bbox_xywh.append(obj)
        confs.append([conf.item()])
        clses.append([cls.item()])

        xywhs = torch.Tensor(bbox_xywh)
        confss = torch.Tensor(confs)
        clses = torch.Tensor(clses)
        # Pass detections to deepsort
        outputs = deepsort.update(xywhs, confss, clses, im0)
`

**Comment by WuPedin** [comment]
Hi 
If you don't want to track some classes, you can modify codes in track.py in line 176. 
You can filter the detection results before deepsort.update().

For example:
```python
classes2track = [0,2,4,6]

for *xyxy, conf, cls in det:
    if cls in classes2track:
        img_h, img_w, _ = im0.shape  # get image shape
        x_c, y_c, bbox_w, bbox_h = bbox_rel(img_w, img_h, *xyxy)
        obj = [x_c, y_c, bbox_w, bbox_h]
        bbox_xywh.append(obj)
        confs.append([conf.item()])
        clses.append([cls.item()])

        xywhs = torch.Tensor(bbox_xywh)
        confss = torch.Tensor(confs)
        clses = torch.Tensor(clses)
        # Pass detections to deepsort
        outputs = deepsort.update(xywhs, confss, clses, im0)
```

**Comment by starsky68** [comment]
> Hi
> If you don't want to track some classes, you can modify codes in track.py in line 176.
> You can filter the detection results before deepsort.update().
> 
> For example:
> 
> ```python
> classes2track = [0,2,4,6]
> 
> for *xyxy, conf, cls in det:
>     if cls in classes2track:
>         img_h, img_w, _ = im0.shape  # get image shape
>         x_c, y_c, bbox_w, bbox_h = bbox_rel(img_w, img_h, *xyxy)
>         obj = [x_c, y_c, bbox_w, bbox_h]
>         bbox_xywh.append(obj)
>         confs.append([conf.item()])
>         clses.append([cls.item()])
> 
>         xywhs = torch.Tensor(bbox_xywh)
>         confss = torch.Tensor(confs)
>         clses = torch.Tensor(clses)
>         # Pass detections to deepsort
>         outputs = deepsort.update(xywhs, confss, clses, im0)
> ```

谢谢你的回复！
